/* =====================================================================
   こども飲食マップ ─ データファイル（このファイルだけを編集します）
   Instagram『せたがやおやこレストラン』(@oyako_de_restaurant) の投稿を基に整理（180件）
   座標=国土地理院 住所検索で作成（生成時のみ・静的保存）。設備・営業状況は投稿時点の情報。
   likes=いいね数（上位20位）。photos=images/内の写真。編集：SHOPSに{ }を追加。画面からは編集不可。
   ===================================================================== */

const SHOPS = [
  {id:1, name:"厳遊庭", area:"広島市", region:"西区古田台", lat:34.394802, lng:132.403336,
   address:"広島県広島市西区古田台2-12-18-12", genre:"和食", photos:[],
   description:"最高の眺望で割烹料理が頂いけます…\n\n【子連れ情報】窓から宮島や広島市街地を一望できる座敷の個室もあるので、お子様と一緒にご利用できます／ベビーカー入店もでき、お子様メニューもあるので安心♫／ベビーカー：あり／座敷：あり／個室：あり／駐車場：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:2, name:"PIZZERIA DINO", area:"世田谷区", region:"", lat:35.667278, lng:139.602509,
   address:"東京都 世田谷区 南烏山 5-11-3", genre:"イタリアン", photos:[],
   description:"千歳烏山徒歩2分、子供食堂にも取り組むナポリピッツァ\n\n【子連れ情報】ベビーカー：要確認※要相談／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:3, name:"cafe The SUN LIVES HERE", likes:15, area:"世田谷区", region:"三軒茶屋", lat:35.640697, lng:139.672272,
   address:"東京都世田谷区三軒茶屋1-27-33", genre:"カフェ", photos:["images/like20.png"],
   description:"世田谷みやげ指定の商品やメディア掲載実績があるチーズケーキ専門店。看板商品CHILKのほかティラミスなどもあり、ベビーカー入店と広いソファ席に対応。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:4, name:"ブーランジェリー ボヌール 三軒茶屋本店", area:"世田谷区", region:"三軒茶屋", lat:35.6423, lng:139.671707,
   address:"東京都世田谷区三軒茶屋1-36-2", genre:"ベーカリー", photos:[],
   description:"コスパがよく種類がとても多い三軒茶屋が本店のパン屋さん\n\n【子連れ情報】ベビーカー：要確認※要確認／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:5, name:"ファーマーズチキン", area:"世田谷区", region:"三軒茶屋", lat:35.642452, lng:139.670837,
   address:"東京都世田谷区三軒茶屋1-37-1 1F", genre:"肉料理", photos:[],
   description:"街の人から愛されるロティサリーチキン専門店\n\n【子連れ情報】店内でも✨テイクアウトもできる絶品ロティサリーチキンです／ベビーカー：なし／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:6, name:"Woodayice", likes:20, area:"世田谷区", region:"三軒茶屋", lat:35.642956, lng:139.666901,
   address:"東京都世田谷区三軒茶屋2-17-12 1F", genre:"スイーツ", photos:["images/like11.png"],
   description:"親子で楽しめるジェラート店特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:7, name:"鴨すき家あかつき", area:"世田谷区", region:"三軒茶屋", lat:35.641777, lng:139.665359,
   address:"東京都世田谷区三軒茶屋2-31-9 マンションパークサイド 1F", genre:"", photos:[],
   description:"三軒茶屋にひっそりと佇む、鴨すきをメインとした鴨、鶏料理専門居酒屋\n\n【子連れ情報】半個室席もあるので、お子様連れの方にもおススメですが、ご予約時にベビーカーの有無やお子様の年齢を店舗へお伝えください♪／ベビーカー：あり／半個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:8, name:"コシラエ", area:"世田谷区", region:"三軒茶屋", lat:35.641029, lng:139.663589,
   address:"東京都世田谷区三軒茶屋2-43-20 錦ビル 1F", genre:"イタリアン", photos:[],
   description:"素材の良さを活かした、心もカラダも笑顔になるイタリアン\n\n【子連れ情報】ベビーカー：あり ご予約の際、お子様のご年齢を教えていただけるとスムーズな対応が可能です。／半個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:9, name:"ミヤハラ", area:"世田谷区", region:"上北沢", lat:35.668274, lng:139.624527,
   address:"東京都世田谷区上北沢3-32-14 小川ビル １Ｆ", genre:"スイーツ", photos:[],
   description:"上北沢駅すぐのパティスリー\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:10, name:"il sole gaO", area:"世田谷区", region:"上北沢", lat:35.668774, lng:139.624878,
   address:"東京都世田谷区上北沢4-13-14 山辺ビル1F", genre:"", photos:[],
   description:"有名ホテル出身シェフのキッズプレートや手作りの離乳食も\n\n【子連れ情報】／離乳食は初期、中期、後期メニューがアレルギー対応の相談もできます／おむつ替え台や授乳室、キッズサービスが充実しているのはもちろん、大人のメニューも大満足な内容です／ベビーカー ：あり／個室：なし／授乳室：あり／おむつ交換台：あり",
   features:{stroller:true, diaper:true, nursing:true, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:11, name:"みつる堂", area:"世田谷区", region:"上馬", lat:35.638855, lng:139.668991,
   address:"東京都世田谷区上馬1-31-14", genre:"", photos:[],
   description:"温かい雰囲気の毎日通いたくなるお店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし／キッズチェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:12, name:"べしゃり", area:"世田谷区", region:"下馬", lat:35.639389, lng:139.68103,
   address:"東京都世田谷区下馬1-27-6", genre:"和食", photos:[],
   description:"世田谷区下馬の住宅街、心と身体が大満足になるお好み焼き店\n\n【子連れ情報】カウンターやテーブル席、個室などシーンに合わせて席を選ぶ事ができます／ベビーカー：要確認※要確認／個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:13, name:"Trattoria MISHIN", area:"世田谷区", region:"下馬", lat:35.641777, lng:139.679474,
   address:"東京都世田谷区下馬1-37-7", genre:"", photos:[],
   description:"世田谷公園近くのログハウス風、一軒家レストラン\n\n【子連れ情報】ベビーカー入店可で1階席のご案内♪／※ ベビーカーのまま入店されたい場合は、お電話下さい。状況によって、入れない場合があります。／ベビーカー ：あり／個室：あり／ソファー席：あり／授乳室：なし／おむつ交換：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:14, name:"FUNGO 三宿本店", area:"世田谷区", region:"下馬", lat:35.641834, lng:139.680878,
   address:"東京都世田谷区下馬1-40-10", genre:"肉料理", photos:[],
   description:"こだわりのハンバーガー、サンドイッチが30種以上\n\n【子連れ情報】オープンテラス席もありペットok／暖かくなったらハンバーガーやサンドイッチをテイクアウトしてピクニックも良いですね☺／ベビーカー：なし／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:15, name:"cafe cafe", area:"世田谷区", region:"下馬", lat:35.640526, lng:139.67482,
   address:"東京都世田谷区下馬2-20-5", genre:"カフェ", photos:[],
   description:"良質で安心な季節の食材を使った手作りメニュー\n\n【子連れ情報】素材の味を活かしたスイーツはテイクアウトもできます／ベビーカー ：なし／半個室：なし／ソファー席：なし／授乳室(施設内)：なし／おむつ交換：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:16, name:"しあわ世のもりあわせ", likes:16, area:"世田谷区", region:"下馬", lat:35.642639, lng:139.677811,
   address:"東京都世田谷区下馬2-31-6", genre:"カフェ", photos:["images/like17.png"],
   description:"こどものひろば公園近くのカフェ。焼き菓子とコーヒーに加え、落書きできる黒板、自由に弾けるピアノ、コワーキングスペース、子ども向け秘密基地が紹介されている。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:17, name:"和kitchen かんな", area:"世田谷区", region:"下馬", lat:35.643337, lng:139.679657,
   address:"東京都世田谷区下馬2-43-11 2F", genre:"スイーツ", photos:[],
   description:"世田谷で大人気のかき氷店\n\n【子連れ情報】子供用の椅子はご用意がないそうなのでご注意を☘／ベビーカー：あり／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:18, name:"GRAND TABLE", area:"世田谷区", region:"下馬", lat:35.644417, lng:139.679352,
   address:"東京都世田谷区下馬2-44-11", genre:"肉料理", photos:[],
   description:"三宿通り沿い、新鮮な牡蠣とグリル料理\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:19, name:"割烹 円", area:"世田谷区", region:"世田谷", lat:35.642605, lng:139.650177,
   address:"東京都世田谷区世田谷1-16-13 エターナル世田谷 102", genre:"和食", photos:[],
   description:"お祝い事にも利用できるお店\n\n【子連れ情報】個室やお座敷席もあり、予約をすれば誕生日、お食い初め、お祝い、法事、会食…／ベビーカー：要確認※要確認／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:true, tatami:true}},
  {id:20, name:"LUCKY STAR COFFEE AND BAR", area:"世田谷区", region:"世田谷", lat:35.64164, lng:139.650757,
   address:"東京都世田谷区世田谷1-16-24 榎本ビル 1F", genre:"カフェ", photos:[],
   description:"丁寧に淹れた美味しいコーヒーを\n\n【子連れ情報】ペットもokで美味しいコーヒー以外にもクラフトビール等もいただけます♪／ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:21, name:"Pego&Co.", likes:20, area:"世田谷区", region:"世田谷", lat:35.64138, lng:139.650757,
   address:"東京都世田谷区世田谷1-16-24 榎本ビル1F", genre:"スイーツ", photos:["images/like11.png"],
   description:"親子で楽しめるジェラート店特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:22, name:"パシモンフリークス", area:"世田谷区", region:"世田谷", lat:35.64183, lng:139.647034,
   address:"東京都世田谷区世田谷1-24-1", genre:"和食", photos:[],
   description:"通し営業でいつでも食べれる定食屋さん\n\n【子連れ情報】ソファー席やベビーカー入店可能なので、子連れの方も時間を問わずおススメです♪／ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:23, name:"カフェ ヤスクーカ", area:"世田谷区", region:"世田谷", lat:35.641754, lng:139.646317,
   address:"東京都世田谷区世田谷1-28-12 グランデュオ世田谷 14-1F", genre:"カフェ", photos:[],
   description:"プリンも人気な落ち着くカフェ\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:24, name:"アボカドーナツ", area:"世田谷区", region:"世田谷", lat:35.641815, lng:139.646423,
   address:"東京都世田谷区世田谷1-28-13 1F", genre:"スイーツ", photos:[],
   description:"アボカドを使ったドーナツ\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:25, name:"LLOYD COFFEE SETAGAYA", area:"世田谷区", region:"世田谷", lat:35.64098, lng:139.643265,
   address:"東京都世田谷区世田谷1-48-1", genre:"カフェ", photos:[],
   description:"本棚に囲まれたコーヒースタンド。スコーンやホットドッグも人気。\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:26, name:"慈恩", area:"世田谷区", region:"世田谷", lat:35.643261, lng:139.646042,
   address:"東京都世田谷区世田谷2-6-1 かつ善ビル 1F", genre:"", photos:[],
   description:"美味しさと健康を両立、こどもから大人まで\n\n【子連れ情報】ベビーカー：要確認※要相談／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:27, name:"VEIGE", area:"世田谷区", region:"世田谷", lat:35.642681, lng:139.654999,
   address:"東京都世田谷区世田谷4-1-13 アウルshoin 1B", genre:"カフェ", photos:[],
   description:"酵素玄米が食べられるカフェ\n\n【子連れ情報】ベビーカー ：あり／個室：なし／ソファー席：あり／授乳室(施設内)：なし／おむつ交換：なし／子供用食器：あり／キッズチェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:28, name:"CITY COFFEE SETAGAYA", likes:19, area:"世田谷区", region:"世田谷", lat:35.645439, lng:139.650818,
   address:"東京都世田谷区世田谷4-17-6", genre:"カフェ", photos:["images/like12.png"],
   description:"赤ちゃんから高齢者まで過ごしやすい地域密着型カフェ。ホットサンドや手作りドリンクを提供し、子ども向けメニュー、絵本・おもちゃ、子ども用食器がある。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:29, name:"庭cafe 443", area:"世田谷区", region:"中町", lat:35.609646, lng:139.645309,
   address:"東京都世田谷区中町2-1-13", genre:"カフェ", photos:[],
   description:"等々力通り沿いにあるペットokのカフェ\n\n【子連れ情報】／テラス席が木々に囲まれた素敵なカフェでペットもok／ベビーカー：あり／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:30, name:"神田きくかわ 上野毛店", area:"世田谷区", region:"中町", lat:35.616196, lng:139.644547,
   address:"東京都世田谷区中町4-20-13", genre:"うなぎ", photos:[],
   description:"昭和22年創業の江戸前うなぎ屋\n\n【子連れ情報】場所柄お子様連れも多く、駐車場もあるので利用しやすいうなぎ屋さん✨／個室もあるので安心です♪／ベビーカー：なし※入り口は階段になっています／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:31, name:"路庵", area:"世田谷区", region:"代沢", lat:35.658474, lng:139.66835,
   address:"東京都世田谷区代沢2-28-9", genre:"そば", photos:[],
   description:"街の人と共に暮らす小さなお蕎麦屋さん\n\n【子連れ情報】ベビーカー：あり／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:32, name:"ボンジョリーナ", area:"世田谷区", region:"代沢", lat:35.658886, lng:139.672806,
   address:"東京都世田谷区代沢2-36-29", genre:"イタリアン", photos:[],
   description:"地元に根付く隠れ家イタリアン\n\n【子連れ情報】池ノ上駅徒歩3分！【テイクアウト】もできる地元人気のイタリア料理店☘／ベビーカー：要確認※要確認／個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:33, name:"台湾料理 光春", area:"世田谷区", region:"代沢", lat:35.660679, lng:139.672775,
   address:"東京都世田谷区代沢2-45-9 飛田ビル 1F", genre:"中華", photos:[],
   description:"TVにも多数出演の人気台湾料理店\n\n【子連れ情報】ベビーカー：なし／半個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:34, name:"art ReG cafe", area:"世田谷区", region:"代沢", lat:35.658104, lng:139.667984,
   address:"東京都世田谷区代沢5-30-10 アール下北沢 2F", genre:"カフェ", photos:[],
   description:"広くておしゃれな店内で味わえるお肉と野菜を中心としたイタリアン\n\n【子連れ情報】ベビーカー：あり／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:35, name:"ナチュラルクレープ 下北沢店", likes:27, area:"世田谷区", region:"代沢", lat:35.659081, lng:139.667343,
   address:"東京都世田谷区代沢5-36-16", genre:"スイーツ", photos:["images/like04.png"],
   description:"素材と手作りにこだわるクレープ専門店。牛乳生地に加えて有機豆乳生地も選べ、人気のいちご・バナナ・チョコホイップなどを楽しめる。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:36, name:"Why Juice? 下北沢店", area:"世田谷区", region:"代田", lat:35.658989, lng:139.663635,
   address:"東京都世田谷区代田2-36-12 BONUS TRACK SOHO-7", genre:"", photos:[],
   description:"お正月で酷使した胃腸に\n\n【子連れ情報】店内に椅子もありますがテイクアウトメイン／ベビーカー：なし／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:37, name:"発酵デパートメント", area:"世田谷区", region:"代田", lat:35.659206, lng:139.664047,
   address:"東京都世田谷区代田2-36-15 BONUS TRACK内", genre:"", photos:[],
   description:"下北沢から10分ほどの発酵デパートメント\n\n【子連れ情報】小上がりのお座敷席もあり、お子様と体に優しい発酵食品をいただくこともできます☘／ベビーカー：要確認※要確認／個室：なし／ソファー席/座敷席：あり小上がりお座敷席／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:38, name:"VERACE", area:"世田谷区", region:"代田", lat:35.657654, lng:139.659348,
   address:"東京都世田谷区代田3-58-7 世田谷代田キャンパス 1F", genre:"イタリアン", photos:[],
   description:"雰囲気の良いイタリア郷土料理のお店\n\n【子連れ情報】※ お子様をお連れの場合は、ご予約時に人数とお年をお伝えください。なお、お子様用のチェアのご用意はありません。／ベビーカー ：あり／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:39, name:"bio ojiyan cafe 下北沢", area:"世田谷区", region:"代田", lat:35.660988, lng:139.665543,
   address:"東京都世田谷区代田5-35-25 １Ｆ", genre:"カフェ", photos:[],
   description:"ドラマsilentのロケ地にもなったおじやのお店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席：あり／授乳室：なし／おむつ交換：なし／子供用食器：あり／キッズチェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:40, name:"KABUTO Shimokita", area:"世田谷区", region:"北沢", lat:35.661823, lng:139.669891,
   address:"東京都世田谷区北沢1-40-6 フィル・パーク下北沢1F", genre:"肉料理", photos:[],
   description:"SNSでバズった4段ハンバーグ\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし ※カウンター席のみ／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:41, name:"すし屋魚真 下北沢店", area:"世田谷区", region:"北沢", lat:35.659004, lng:139.668335,
   address:"東京都世田谷区北沢2-1-1 ツバサマンション 1F", genre:"寿司", photos:[],
   description:"魚屋が母体の寿司店。日替わりの鮮魚と赤酢のシャリが特徴。\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:42, name:"なんばん亭", area:"世田谷区", region:"北沢", lat:35.660717, lng:139.667984,
   address:"東京都世田谷区北沢2-12-3 石川ビル 2F", genre:"和食", photos:[],
   description:"絶品の“四角いお好み焼き” プロの手捌きまでご堪能あれ\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:43, name:"nine9style hamburger&bar", area:"世田谷区", region:"北沢", lat:35.66021, lng:139.666641,
   address:"東京都世田谷区北沢2-18-5 Neビル 3F", genre:"", photos:[],
   description:"佐賀の伊万里牛100% hamburger\n\n【子連れ情報】ベビーカー入店もできるので子連れでもおススメのお店です✨／ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:44, name:"&ROLL", area:"世田谷区", region:"北沢", lat:35.660301, lng:139.667343,
   address:"東京都世田谷区北沢2-19-17 サワダヤビル ３Ｆ", genre:"カフェ", photos:[],
   description:"自家製デザートやカフェメニューはもちろん、カクテルやクラフトビールなどアルコールも充実\n\n【子連れ情報】ソファー席や個室もあるので、お子様連れは事前予約がおススメです／ベビーカー：あり／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:45, name:"KITADES TACOS 下北沢店", area:"世田谷区", region:"北沢", lat:35.660793, lng:139.666656,
   address:"東京都世田谷区北沢2-21-22", genre:"", photos:[],
   description:"下北沢駅すぐ！カジュアルに楽しめるメキシカンタコスのお店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:46, name:"歓迎 下北沢店", area:"世田谷区", region:"北沢", lat:35.661869, lng:139.667358,
   address:"東京都世田谷区北沢2-24-2", genre:"中華", photos:[],
   description:"蒲田名物羽根付き餃子をはじめとする本格中華\n\n【子連れ情報】下北沢駅中央改札すぐベビーカーokの本格中華／テイクアウトもできますよ♪／ベビーカー：あり／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:47, name:"音倉", area:"世田谷区", region:"北沢", lat:35.662323, lng:139.66684,
   address:"東京都世田谷区北沢2-26-23 EL・NIU Ｂ１", genre:"カフェ", photos:[],
   description:"ライブハウスのあるオーガニックカフェ\n\n【子連れ情報】赤ちゃん連れにも安心して利用していただけるようにと、お手洗いにはおむつ替えシートも設置されているそうです／お店は地下にあり、エレベーターはないのでベビーカーでの利用はご注意ください✨／ベビーカー：なし 地下のお店でエレベーター無し／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：要確認 おむつ替えシート有り",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:48, name:"農民カフェ 下北沢店", area:"世田谷区", region:"北沢", lat:35.663029, lng:139.665741,
   address:"東京都世田谷区北沢2-27-8", genre:"カフェ", photos:[],
   description:"無農薬野菜中心の安心メニュー\n\n【子連れ情報】お子様メニューや座敷席もあるので、お子様連れにもとてもおススメ✨／ベビーカー ：あり／個室：あり／授乳室：なし／おむつ交換台：なし／子供用食器：あり／駐車場：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:true, privateRoom:true, tatami:false}},
  {id:49, name:"DOGBERRY", area:"世田谷区", region:"北沢", lat:35.662964, lng:139.667053,
   address:"東京都世田谷区北沢2-29-16 高木ビル 1F", genre:"カフェ", photos:[],
   description:"下北沢の隠れ家バル\n\n【子連れ情報】お昼は家族連れやペット連れで賑わうカフェスタイル✨／ベビーカー：あり／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:50, name:"かまいキッチン", area:"世田谷区", region:"北沢", lat:35.663132, lng:139.668594,
   address:"東京都世田谷区北沢2-33-6 第２ミチルビル２Ｆ", genre:"カフェ", photos:[],
   description:"小上がり座席のあるママと赤ちゃんに優しいカフェ\n\n【子連れ情報】座敷にはちゃぶ台が置いてありどこかレトロで落ち着きのある雰囲気です♪／キッズサービスも充実しており、おむつ替え台や授乳室、バンボやおもちゃもあるので子供達も飽きずに楽しむことができます／ベビーカー ：あり／個室：なし／授乳室：あり／おむつ交換台：あり／子供用食器：あり",
   features:{stroller:true, diaper:true, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:51, name:"猫米", area:"世田谷区", region:"北沢", lat:35.667442, lng:139.665955,
   address:"東京都世田谷区北沢4-17-7", genre:"中華", photos:[],
   description:"下北沢で本場台湾の料理をフルーツビールとともに堪能\n\n【子連れ情報】テイクアウトのお弁当や台湾茶はお花見にぴったりですよ／ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:52, name:"ひぐちや", likes:23, area:"世田谷区", region:"南烏山", lat:35.667252, lng:139.602478,
   address:"東京都世田谷区南烏山5丁目12-11", genre:"", photos:["images/like08.png"],
   description:"生産者や食材の背景を大切にし、一皿ごとの物語を感じられる料理店。落ち着いた店内で、ベビーカー入店と離乳食の持ち込みに対応。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:53, name:"村上食堂", area:"世田谷区", region:"南烏山", lat:35.670879, lng:139.597549,
   address:"東京都世田谷区南烏山6-25-11 セラグリオ烏山 101", genre:"イタリアン", photos:[],
   description:"千歳烏山駅の隠れ家的イタリアン\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:54, name:"プリン屋ほほえみキッチン", likes:18, area:"世田谷区", region:"南烏山", lat:35.670845, lng:139.597839,
   address:"東京都世田谷区南烏山6-27-13", genre:"スイーツ", photos:["images/like14.png"],
   description:"2024年指定の『世田谷みやげ』特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:55, name:"Pulcino", area:"世田谷区", region:"南烏山", lat:35.670166, lng:139.599213,
   address:"東京都世田谷区南烏山6-30-7", genre:"イタリアン", photos:[],
   description:"石窯ピザもパスタも美味しいイタリアン\n\n【子連れ情報】ベビーカー：あり／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:56, name:"AJIANA 千歳烏山", area:"世田谷区", region:"南烏山", lat:35.668877, lng:139.599533,
   address:"東京都世田谷区南烏山6-4-12 サンハイツ烏山 1F", genre:"タイ・アジア", photos:[],
   description:"オシャレな雰囲気の店内で本格的なタイ&インド料理を堪能！\n\n【子連れ情報】全120席あり、座敷席からソファー席、テラス席もありお子様向けメニューもあるので子連れでの利用も安心です／ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:57, name:"そば処 丸屋", area:"世田谷区", region:"喜多見", lat:35.635677, lng:139.58931,
   address:"東京都世田谷区喜多見8-16-8", genre:"そば", photos:[],
   description:"北見駅徒歩3〜4分/蕎麦屋・丸屋\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:58, name:"カンナカフェ", area:"世田谷区", region:"大原", lat:35.668098, lng:139.661392,
   address:"東京都世田谷区大原1-25-4 エタニティ大原 1F", genre:"カフェ", photos:[],
   description:"ハワイのローカルカフェをイメージしたウッディな空間\n\n【子連れ情報】ベビーカー：要確認※要相談／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：あり",
   features:{stroller:false, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:59, name:"Bistro Papillons", area:"世田谷区", region:"大原", lat:35.672565, lng:139.661469,
   address:"東京都世田谷区大原1-63-9 アーク笹塚ビル 1F", genre:"フレンチ", photos:[],
   description:"代田橋徒歩5分の創作フレンチ\n\n【子連れ情報】ベビーカー：なし ※入り口段差あり／半個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:60, name:"チャオサイゴン パリバール", area:"世田谷区", region:"大原", lat:35.671597, lng:139.658493,
   address:"東京都世田谷区大原2-27-29 メゾン代田橋 2F", genre:"タイ・アジア", photos:[],
   description:"本格的なアジア料理の数々を、世界から取り揃えたドリンクと共に味わえる\n\n【子連れ情報】ベビーカー：あり／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:true, tatami:true}},
  {id:61, name:"三茶ジャッキー小籠包", area:"世田谷区", region:"太子堂", lat:35.641525, lng:139.673401,
   address:"東京都世田谷区太子堂1-15-13 1F", genre:"中華", photos:[],
   description:"三茶で小籠包といえばココ‼ミシュランビブグルマン取得餃子マニア系列店\n\n【子連れ情報】ベビーカー：要確認※要確認／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:62, name:"瀬戸内バル Collabo", area:"世田谷区", region:"太子堂", lat:35.64566, lng:139.675705,
   address:"東京都世田谷区太子堂1-6-9 1F", genre:"バー", photos:[],
   description:"瀬戸内海の食材にこだわる地中海料理\n\n【子連れ情報】小上がり席のような半個室の席や子供も食べれるメニューが多いとの口コミも多いお店／ベビーカー：あり／半個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:63, name:"やおやのファミリーレストラン", likes:17, area:"世田谷区", region:"太子堂", lat:35.645142, lng:139.670547,
   address:"東京都世田谷区太子堂2-17-9 the b 三軒茶屋 2F", genre:"", photos:["images/like16.png"],
   description:"旬のオーガニック野菜や伝統野菜を使ったサラダバーと40種類を超えるメニューが特徴。小上がり、個室、子ども用椅子・食器、子ども向けメニュー、おむつ交換設備がある。",
   features:{stroller:true, diaper:true, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:true, privateRoom:true, tatami:true}},
  {id:64, name:"イルピッツァイオーロ", area:"世田谷区", region:"太子堂", lat:35.644409, lng:139.668732,
   address:"東京都世田谷区太子堂4-20-7 QG三軒茶屋 1F", genre:"イタリアン", photos:[],
   description:"薪窯で焼くピッツァが自慢のお店\n\n【子連れ情報】ベビーカー入店が出来ないので注意が必要ですが、テラス席もあるので天気の良い日はテラス席がおススメです☺／ベビーカー：なし／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:65, name:"リザラン 三軒茶屋", area:"世田谷区", region:"太子堂", lat:35.644352, lng:139.670715,
   address:"東京都世田谷区太子堂4-23-11 ジェムズ三軒茶屋 2F", genre:"スペイン", photos:[],
   description:"三軒茶屋駅徒歩１分 、スペイン料理\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:66, name:"ペスケリア", area:"世田谷区", region:"太子堂", lat:35.644913, lng:139.670502,
   address:"東京都世田谷区太子堂4-24-15 1F", genre:"イタリアン", photos:[],
   description:"本格南イタリア料理を三軒茶屋で\n\n【子連れ情報】お子様メニューや一部席はベビーカーもokなのです／ベビーカー：あり ※ ベビーカーを置けるお席は限られます。ベビーカーお持ち込みご希望の方はご予約の際明記いただけると助かります。／個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:true, privateRoom:true, tatami:false}},
  {id:67, name:"たけや", area:"世田谷区", region:"太子堂", lat:35.645275, lng:139.669617,
   address:"東京都世田谷区太子堂4-26-7", genre:"そば", photos:[],
   description:"三軒茶屋で長く続くお蕎麦屋さん\n\n【子連れ情報】半個室の席もあるのでお子様連れの方は予約をしての利用がおススメです☘／ベビーカー：要確認※要確認／半個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:68, name:"KIKUYA", area:"世田谷区", region:"太子堂", lat:35.647373, lng:139.669083,
   address:"東京都世田谷区太子堂5-1-12 1F", genre:"", photos:[],
   description:"自家製クラフトビールと創作スパイス料理\n\n【子連れ情報】ベビーカー：あり／個室：あり／ソファー席：あり／授乳室：なし／おむつ交換：なし／子供用食器：なし／キッズチェアー：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:69, name:"ICHIBIKO", likes:18, area:"世田谷区", region:"太子堂", lat:35.646008, lng:139.665802,
   address:"東京都世田谷区太子堂5-8-3", genre:"", photos:["images/like14.png"],
   description:"2024年指定の『世田谷みやげ』特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:70, name:"奥沢サクレクール", area:"世田谷区", region:"奥沢", lat:35.600864, lng:139.671722,
   address:"東京都世田谷区奥沢3-12-6", genre:"フレンチ", photos:[],
   description:"本場星付きレストランで身に付けた技と知識の家庭的なフレンチ\n\n【子連れ情報】ベビーカー -／個室：なし／授乳室：なし／おむつ交換台：なし／子供用食器-／駐車場：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:71, name:"little mouse cafe dining", area:"世田谷区", region:"奥沢", lat:35.603477, lng:139.67157,
   address:"東京都世田谷区奥沢4-27-12 パトラ奥沢 B1F", genre:"カフェ", photos:[],
   description:"奥沢にある隠れ家レストラン\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席：あり／授乳室：なし／おむつ交換：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:72, name:"自由が丘 みつばち", area:"世田谷区", region:"奥沢", lat:35.606174, lng:139.669418,
   address:"東京都世田谷区奥沢5-20-17 ユングフラウビル2F", genre:"", photos:[],
   description:"子連れに優しいサービスのある奥沢のお店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：あり／子供用食器：あり／お子様用チェアー：なし",
   features:{stroller:true, diaper:true, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:73, name:"AmiCono", likes:20, area:"世田谷区", region:"奥沢", lat:35.60619, lng:139.668106,
   address:"東京都世田谷区奥沢5-27-9", genre:"スイーツ", photos:["images/like11.png"],
   description:"親子で楽しめるジェラート店特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:74, name:"THE ARCHIVE CAFE", area:"世田谷区", region:"奥沢", lat:35.605457, lng:139.661697,
   address:"東京都世田谷区奥沢7-19-9 2F", genre:"カフェ", photos:[],
   description:"素材にこだわる居心地の良いカフェ\n\n【子連れ情報】2Fのお店なのでベビーカーの場合にはご注意を／ベビーカー：なし／個室：なし／ソファー席：あり／授乳室：なし／おむつ交換：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:75, name:"O RESTO la med.", area:"世田谷区", region:"奥沢", lat:35.603073, lng:139.66069,
   address:"東京都世田谷区奥沢8-13-9 タウンハイツ九品仏I-B01", genre:"タイ・アジア", photos:[],
   description:"自由が丘・九品仏の地中海料理\n\n【子連れ情報】ランチタイムはキッズメニューも☘／おむつ交換台やベビーチェアの用意もあり、子供連れにとても優しいお店です／ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：あり",
   features:{stroller:true, diaper:true, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:76, name:"ベアピザ ポコ", area:"世田谷区", region:"宮坂", lat:35.648056, lng:139.64473,
   address:"東京都世田谷区宮坂1-24-6", genre:"イタリアン", photos:[],
   description:"食べると元気になるピザ屋さん\n\n【子連れ情報】ベビーカー：要確認※要確認／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：あり",
   features:{stroller:false, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:77, name:"バレアリック飲食店", area:"世田谷区", region:"宮坂", lat:35.649654, lng:139.645355,
   address:"東京都世田谷区宮坂1-38-19", genre:"和食", photos:[],
   description:"どこか南の島の郊外に佇んでそうなニュー大衆食堂＋酒場\n\n【子連れ情報】お子様連れ歓迎&ペット全席OK！／ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:78, name:"Chouette torréfacteur laboratoire", area:"世田谷区", region:"宮坂", lat:35.650429, lng:139.645584,
   address:"東京都世田谷区宮坂1-39-11", genre:"カフェ", photos:[],
   description:"お子様歓迎のこだわりのコーヒー専門店\n\n【子連れ情報】自然素材で作られたホットドッグや焼き菓子、キッズドリンクもあるのでお子様と立ち寄るのにもおすすめです☺／ベビーカー：なし／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:79, name:"みんなのテーブル", area:"世田谷区", region:"宮坂", lat:35.652149, lng:139.636795,
   address:"東京都世田谷区宮坂3-12-4 ＤＯＭ経堂 2F", genre:"", photos:[],
   description:"居心地の良い隠れ家レストラン\n\n【子連れ情報】お子様メニューやベビーカー入店も可能なのでお子様連れでも利用しやすいところもポイント☺／ベビーカー：あり／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:80, name:"ホットケーキつるばみ舎", area:"世田谷区", region:"宮坂", lat:35.652596, lng:139.637924,
   address:"東京都世田谷区宮坂3-9-4 アルカディア経堂 1F", genre:"カフェ", photos:[],
   description:"経堂で老若男女問わず愛されるカフェ\n\n【子連れ情報】ベビーカー：要確認 ※要確認／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:81, name:"RIGUTTA", area:"世田谷区", region:"尾山台", lat:35.606609, lng:139.653534,
   address:"東京都世田谷区尾山台3-22-13 2F", genre:"イタリアン", photos:[],
   description:"尾山台駅から徒歩１分に構える本格イタリアンレストラン\n\n【子連れ情報】ベビーカー：要確認※要確認／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:82, name:"555", area:"世田谷区", region:"尾山台", lat:35.606533, lng:139.654099,
   address:"東京都世田谷区尾山台3-34-1", genre:"", photos:[],
   description:"元CAさんがヨーロッパの食文化を発信するテイクアウト惣菜専門店\n\n【子連れ情報】／ヨーロッパ中の美味しい食材を取り入れたテイクアウト惣菜専門店です♪",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:83, name:"VENTO OTTO", area:"世田谷区", region:"尾山台", lat:35.603355, lng:139.653748,
   address:"東京都世田谷区尾山台3-7-4 スカイガーデン尾山台", genre:"イタリアン", photos:[],
   description:"わんちゃんもokな本格イタリアン\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:84, name:"喫茶レスト", area:"世田谷区", region:"弦巻", lat:35.637608, lng:139.643967,
   address:"東京都世田谷区弦巻3丁目16番8号", genre:"", photos:[],
   description:"図書館、プラネタリウム利用時の休憩に\n\n【子連れ情報】ベビーカー：要確認要相談 ベビーカーで行くと椅子を移動してくださるそうです。／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：あり 図書館内の多目的トイレ内／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:true, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:85, name:"Trattoria 成城", area:"世田谷区", region:"成城", lat:35.639877, lng:139.596848,
   address:"東京都世田谷区成城5-1-23", genre:"イタリアン", photos:[],
   description:"子供連れ用の親子スペースや個室も備えたイタリア料理店\n\n【子連れ情報】／小上がり席のような半個室の席や子供も食べれるメニューが多いとの口コミも多いお店／日の光が差し込むテーブル席と個室があり、仕切られた空間を親子スペースとしてご利用でき、お子様連れには回りを気にせずにお食事できる空間です／ベビーカー：あり／半個室：あり／ソファー席/座敷席：あり／授乳室：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:86, name:"とんかつ椿", area:"世田谷区", region:"成城", lat:35.642761, lng:139.596436,
   address:"東京都世田谷区成城5-15-3", genre:"和食", photos:[],
   description:"成城住宅街の美味しいとんかつ屋さん\n\n【子連れ情報】ベビーカー入店は出来ますが、空いている席によってはお子様はベビーカーより出てのご利用をお願いする場合が御座います、とのこと♪／テイクアウトもおススメです／ベビーカー：あり ※ 空いている席によってはお子様はベビーカーより出てのご利用をお願いする場合が御座います。／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:87, name:"日本料理 成城きた山", area:"世田谷区", region:"成城", lat:35.641499, lng:139.596573,
   address:"東京都世田谷区成城6-16-14", genre:"和食", photos:[],
   description:"美味しい和食 お昼はご褒美ランチ、夜はご接待やアニバーサリー等に\n\n【子連れ情報】駐車場や個室もあるので、贅沢なランチやお祝い事にもぴったり☺／ベビーカー：要確認※要確認／個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:true, tatami:false}},
  {id:88, name:"setlip", likes:18, area:"世田谷区", region:"成城", lat:35.640942, lng:139.601089,
   address:"東京都世田谷区成城6-3-14", genre:"スペイン", photos:["images/like15.png"],
   description:"成城の住宅街にあるスペイン料理店。カウンター、テーブル、ソファ・座敷、テラスと席の選択肢があり、ベビーカー入店と子ども用チェアに対応。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:89, name:"キナヤ", area:"世田谷区", region:"成城", lat:35.64991, lng:139.594925,
   address:"東京都世田谷区成城9-26-6", genre:"", photos:[],
   description:"こだわりの無農薬野菜を使ったマクロビご飯\n\n【子連れ情報】ベビーカー：要確認※要確認／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：要確認※要確認",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:90, name:"ルレ・サクラ", area:"世田谷区", region:"新町", lat:35.627842, lng:139.646667,
   address:"東京都世田谷区新町1-36-9 １Ｆ", genre:"フレンチ", photos:[],
   description:"カジュアルにもフォーマルにも。自由に本格フレンチを愉しめる、“さくら”の街の“休憩所”\n\n【子連れ情報】ベビーカー：要確認※要相談／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：あり",
   features:{stroller:false, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:91, name:"ワイガヤ 桜新町店", area:"世田谷区", region:"新町", lat:35.631695, lng:139.647095,
   address:"東京都世田谷区新町2-25-17 平和ビル１階", genre:"肉料理", photos:[],
   description:"桜新町駅徒歩3分、ステーキとハンバーグのお店\n\n【子連れ情報】店内は広々としているので、ベビーカーok♪／ベビーカー：あり／半個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:92, name:"OGAWA COFFEE LABORATORY 桜新町", area:"世田谷区", region:"新町", lat:35.632996, lng:139.645721,
   address:"東京都世田谷区新町3-23-8 エスカリエ桜新町 1F", genre:"カフェ", photos:[],
   description:"広々としたモダンな空間でコーヒータイムを\n\n【子連れ情報】店内は広々としているのでベビーカー入店もできます／ベビーカー：あり／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:93, name:"ASIAN MEAT & GRILL 明大前店", area:"世田谷区", region:"松原", lat:35.66927, lng:139.650635,
   address:"東京都世田谷区松原1-37-17 米沢ビル 1F", genre:"", photos:[],
   description:"今日はお肉が食べたい！日にぴったり\n\n【子連れ情報】店内も広くベビーカーでも入店可能です／ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:94, name:"NIKSEN", area:"世田谷区", region:"松原", lat:35.66877, lng:139.650925,
   address:"東京都世田谷区松原1-38-3 山本ビル 202", genre:"", photos:[],
   description:"野菜たっぷりでバランスの取れたお昼ごはんとお夕飯を\n\n【子連れ情報】ベビーカーokですが、階段があるのでスタッフさんへお声がけが必要です／ベビーカー：あり※スタッフさんへお声がけが必要／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:95, name:"オネヨ", area:"世田谷区", region:"松原", lat:35.662594, lng:139.655014,
   address:"東京都世田谷区松原5-2-5 1F", genre:"韓国", photos:[],
   description:"リラックスしながら味わう本格韓国料理\n\n【子連れ情報】ベビーカー：あり／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:96, name:"ふれあいカフェ うめとぴあ", area:"世田谷区", region:"松原", lat:35.657021, lng:139.649582,
   address:"東京都世田谷区松原6-37-10", genre:"カフェ", photos:[],
   description:"世田谷区の保健医療福祉総合プラザ、うめとぴあの1階にある広々としたカフェです\n\n【子連れ情報】／そして、介護食、離乳食もあるとのこと！／ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：あり／おむつ交換スペース：あり",
   features:{stroller:true, diaper:true, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:97, name:"PASTA & WINE カカポ", area:"世田谷区", region:"桜", lat:35.640163, lng:139.640182,
   address:"東京都世田谷区桜3-2-18 太陽ハイツ 1F", genre:"イタリアン", photos:[],
   description:"子連れに優しい生麺パスタと美味なアラカルトが自慢のお店\n\n【子連れ情報】ベビーカーはもちろん、子供用のイスや食器、お子様メニューも用意されているのでお子様連れで美味しい食事を楽しめます／ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:98, name:"木々", area:"世田谷区", region:"桜上水", lat:35.664833, lng:139.631165,
   address:"東京都世田谷区桜上水4-20-19", genre:"和食", photos:[],
   description:"四季のお料理を楽しめる日本料理店\n\n【子連れ情報】全て個室なので子連れでも安心／ベビーカー：要確認 ※要確認／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:99, name:"LALALA CAFE", area:"世田谷区", region:"桜丘", lat:35.646271, lng:139.624176,
   address:"東京都世田谷区桜丘2-19-10 1F", genre:"カフェ", photos:[],
   description:"安心してくつろげるカフェ\n\n【子連れ情報】ベビーカー：要確認 要確認／個室：なし／ソファー席：要確認／授乳室：なし／おむつ交換：なし／子供用食器：なし／キッズチェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:100, name:"そば一仁", area:"世田谷区", region:"桜丘", lat:35.646671, lng:139.622589,
   address:"東京都世田谷区桜丘2-26-11", genre:"そば", photos:[],
   description:"千歳船橋駅より徒歩3分の自家製粉手打ちの蕎麦屋\n\n【子連れ情報】ベビーカー：あり／半個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:101, name:"PIZZERIA CIRO 桜新町", area:"世田谷区", region:"桜新町", lat:35.629993, lng:139.644012,
   address:"東京都世田谷区桜新町1-8-9 丸新ビル 1F", genre:"イタリアン", photos:[],
   description:"桜新町駅5分のNapoli製の薪窯で焼き上げる絶品ピッツァ\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:102, name:"NEIGHBOR", area:"世田谷区", region:"桜新町", lat:35.630844, lng:139.641022,
   address:"東京都世田谷区桜新町2-26-2 水車の家 1F", genre:"フレンチ", photos:[],
   description:"音楽ライブも行っているフレンチレストラン\n\n【子連れ情報】ベビーカー ：あり／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし／キッズチェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:103, name:"Cafe La Bohème 桜新町", area:"世田谷区", region:"桜新町", lat:35.631721, lng:139.644257,
   address:"東京都世田谷区桜新町2-9-2 1F", genre:"カフェ", photos:[],
   description:"人気のカフェ、ラ・ボエムの桜新町 店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:104, name:"HIGH FIVE CAFE", area:"世田谷区", region:"梅丘", lat:35.654774, lng:139.653305,
   address:"東京都世田谷区梅丘1-14-5", genre:"カフェ", photos:[],
   description:"梅ヶ丘駅徒歩約2分女性に人気のカフェ\n\n【子連れ情報】店内は広く、ゆったり過ごすことができ、子供連れにも嬉しい子供用メニューや食器、椅子等が揃っています✨／ベビーカー：あり／半個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:105, name:"洋風料理店 T.A.N.A.K.A", area:"世田谷区", region:"梅丘", lat:35.655556, lng:139.652679,
   address:"東京都世田谷区梅丘1-24-13 サンライズ小池 1F", genre:"バー", photos:[],
   description:"世界のビールやお手頃ワイン …梅ヶ丘徒歩1分のお店\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：あり",
   features:{stroller:false, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:106, name:"八代井亭", area:"世田谷区", region:"池尻", lat:35.649254, lng:139.681458,
   address:"東京都世田谷区池尻3-20-2 柳盛堂Ⅱ Ｂ１Ｆ", genre:"肉料理", photos:[],
   description:"池尻大橋でしゃぶしゃぶ・すきやき・ステーキなど厳選和牛を味わう\n\n【子連れ情報】店内は、カウンター席、テーブル席、お座敷個室を設けており、ゆったりとくつろげる空間♪／ベビーカー：なし ※地下のお店になりますのでご注意ください。／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:107, name:"Lien／Prive de Lien", area:"世田谷区", region:"池尻", lat:35.651302, lng:139.68103,
   address:"東京都世田谷区池尻3-5-22 グレースマンション 1F", genre:"フレンチ", photos:[],
   description:"住宅街にひっそりと佇む「Lien」「Prive de Lien」\n\n【子連れ情報】個室もあるので、子連れでもフレンチを楽しめます♪／ベビーカー：要確認※要確認／個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:108, name:"Kuppography Cafe", area:"世田谷区", region:"深沢", lat:35.617779, lng:139.651703,
   address:"東京都世田谷区深沢5-1-8", genre:"カフェ", photos:[],
   description:"素敵な写真を撮影してくれるフォトスタジオ併設のおしゃれカフェ\n\n【子連れ情報】ベビーカー ：あり／半個室：なし／ソファー席：なし／授乳室(施設内)：なし／おむつ交換：なし／子供用食器：なし／キッズチェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:109, name:"創作和食 田", area:"世田谷区", region:"深沢", lat:35.621571, lng:139.652954,
   address:"東京都世田谷区深沢6-14-2 医王寺敷地内", genre:"和食", photos:[],
   description:"お寺の敷地内にある創作和食\n\n【子連れ情報】お寺の敷地内ということもあり、入り口から高級料亭のようですが、実はペットもokで普段使いからお祝いまで幅広く利用できる和食店です☘／駐車場もあります／ベビーカー：要確認※要確認／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:110, name:"FUSHATHÉ LOUNGE", area:"世田谷区", region:"瀬田", lat:35.617104, lng:139.630783,
   address:"東京都世田谷区瀬田2-10-5 瀬田の杜Garden&Terrace 1F", genre:"タイ・アジア", photos:[],
   description:"スリランカで厳選した香り高い紅茶\n\n【子連れ情報】店内は明るく開放的で、テラス席もありペットok／ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:111, name:"HEIDI'S BAKE", area:"世田谷区", region:"瀬田", lat:35.620483, lng:139.630814,
   address:"東京都世田谷区瀬田2-27-6 三立ビル 2F", genre:"ベーカリー", photos:[],
   description:"台湾人パティシエが作る焼き菓子店\n\n【子連れ情報】ベビーカー：ありエレベーター有／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:112, name:"HONOKA", area:"世田谷区", region:"瀬田", lat:35.620331, lng:139.630768,
   address:"東京都世田谷区瀬田2-28-10 イケダハイツビル 1F", genre:"カフェ", photos:[],
   description:"用賀駅徒歩8分のエディブルフラワーがキレイなカフェ\n\n【子連れ情報】ベビーカー：要確認※要確認／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:113, name:"CHICHI CAFE", area:"世田谷区", region:"玉川", lat:35.608227, lng:139.630432,
   address:"東京都世田谷区玉川1-2-8", genre:"カフェ", photos:[],
   description:"玉川沿いにある穴場カフェ\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席：あり／授乳室：なし／おむつ交換：なし／子供用食器：あり／ベビーチェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:114, name:"BLUE POPPY BAKERY", area:"世田谷区", region:"玉川", lat:35.612778, lng:139.629974,
   address:"東京都世田谷区玉川2-12-7 NSEビル 1A", genre:"ベーカリー", photos:[],
   description:"あれも！これも！と悩んでしまう圧倒的なパンの種類\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:115, name:"タイ屋台999 二子玉川ライズS.C店", area:"世田谷区", region:"玉川", lat:35.611366, lng:139.628525,
   address:"東京都世田谷区玉川2-21-1 二子玉川ライズタウンフロント 7F", genre:"タイ・アジア", photos:[],
   description:"人生最高のタイ屋台のおばちゃんの味\n\n【子連れ情報】一見屋台風の外観やタイ料理…ということで、入り辛いイメージがありましたが、店内は広々ベビーカー入店okで、お子様メニューもあるので、安心して利用できます／ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：あり／おむつ交換スペース：あり／子供用食器：あり",
   features:{stroller:true, diaper:true, nursing:true, babyChair:false, kidsMenu:true, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:116, name:"長次郎", area:"世田谷区", region:"玉川", lat:35.612579, lng:139.627243,
   address:"東京都世田谷区玉川2-23-1 二子玉川ライズドッグウッドプラザ 8F", genre:"寿司", photos:[],
   description:"シックでおしゃれな内装が特徴的な回転すし屋さん\n\n【子連れ情報】施設内には授乳室やおむつ替えの場所、駐車場もあるので子連れで安心してご利用できますよ☺／ベビーカー：要確認※要確認／個室：なし／ソファー席/座敷席：なし／授乳室：あり／おむつ交換スペース：あり／子供用食器：要確認※要確認",
   features:{stroller:false, diaper:true, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:117, name:"bills 二子玉川", area:"世田谷区", region:"玉川", lat:35.615055, lng:139.627686,
   address:"東京都世田谷区玉川2-27-5 玉川高島屋S・Cマロニエコート 3F", genre:"", photos:[],
   description:"シドニー発オールディカジュアルダイニング\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:118, name:"DAVELLO", area:"世田谷区", region:"玉川", lat:35.613506, lng:139.625092,
   address:"東京都世田谷区玉川3-13-7 柳小路南角 1F", genre:"バー", photos:[],
   description:"路地裏のワインバル\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:119, name:"蒸し中華 STEAMAN", likes:16, area:"世田谷区", region:"玉川", lat:35.613834, lng:139.625443,
   address:"東京都世田谷区玉川3-14-8 A*G二子玉川 2F", genre:"中華", photos:["images/like18.png"],
   description:"蒸し料理とヌーベルシノワを組み合わせた中華料理店。エレベーターがあり、ルーローハンはスパイスを抜いて子ども向けに調整可能。子ども用食器とソファ席もある。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:120, name:"アッチャカーナ", likes:26, area:"世田谷区", region:"玉川", lat:35.613652, lng:139.626984,
   address:"東京都世田谷区玉川3-17-1 玉川タカシマヤ 1F", genre:"カレー", photos:["images/like05.png"],
   description:"スパイスの効いたカレーで知られ、テレビ番組でも紹介された店。甘口カレーがあり、高島屋内の授乳室・おむつ交換設備も利用できる。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:121, name:"九つ井 玉川店", area:"世田谷区", region:"玉川", lat:35.613587, lng:139.627097,
   address:"東京都世田谷区玉川3-17-1 玉川タカシマヤ 東館 B1F", genre:"そば", photos:[],
   description:"ゆったりと落ち着いた雰囲気の中、美味しいお蕎麦をいただけます\n\n【子連れ情報】予約ができ(コース料理のみ)座敷のお席なので、赤ちゃんや子連れでの利用もしやすいです☘／ベビーカー：要確認※要確認／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:122, name:"365日とCOFFEE", likes:16, area:"世田谷区", region:"玉川", lat:35.613457, lng:139.627097,
   address:"東京都世田谷区玉川3-17-1 玉川高島屋S.C.本館2階", genre:"カフェ", photos:["images/like19.png"],
   description:"人気ベーカリー365日が手掛けるパンとコーヒーの店。ソファ席があり、玉川高島屋内の授乳室、おむつ交換設備、駐車場を利用できる。",
   features:{stroller:true, diaper:true, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:123, name:"GELATO PIQUE CAFE 玉川高島屋S・C店", likes:25, area:"世田谷区", region:"玉川", lat:35.613392, lng:139.626984,
   address:"東京都世田谷区玉川3-17-1 玉川高島屋S・C 南館 B1F", genre:"カフェ", photos:["images/like06.png"],
   description:"座敷、キッズスペース、子ども用チェア、授乳室などが揃う子連れ向けカフェ。もちもちしたクレープと、ブランドらしいかわいい店内が特徴。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:124, name:"The Veranda 玉川高島屋S・C店", area:"世田谷区", region:"玉川", lat:35.613457, lng:139.626871,
   address:"東京都世田谷区玉川3-17-1 玉川高島屋S・C南館9F", genre:"", photos:[],
   description:"玉川高島屋9階の南国レストラン。眺望とテラス席が魅力。\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席/座敷席：あり／授乳室：あり／おむつ交換スペース：あり／子供用食器：なし／お子様用チェアー：あり",
   features:{stroller:false, diaper:true, nursing:true, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:125, name:"壁の穴", area:"世田谷区", region:"玉川", lat:35.613587, lng:139.626871,
   address:"東京都世田谷区玉川3-17-1 玉川高島屋S・C南館9階", genre:"", photos:[],
   description:"たらこスパゲッティ発祥の店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：あり 高島屋内／おむつ交換スペース：あり 高島屋内／子供用食器：あり／お子様用チェアー：あり",
   features:{stroller:true, diaper:true, nursing:true, babyChair:true, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:126, name:"酉たか", area:"世田谷区", region:"玉川", lat:35.615974, lng:139.624893,
   address:"東京都世田谷区玉川3-21-21 ハイムカワベ 1F", genre:"肉料理", photos:[],
   description:"完全個室で子連れでも楽しめる焼鳥\n\n【子連れ情報】／また、希少部位も豊富！店内には、調理風景を眺められるカウンター席と、お子様連れに最適な完全個室も／ベビーカー：あり／個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:127, name:"タマクーヘン", likes:28, area:"世田谷区", region:"玉川", lat:35.615162, lng:139.626358,
   address:"東京都世田谷区玉川3丁目20-1 名川ビル1F", genre:"カフェ", photos:["images/like03.png"],
   description:"米粉を使ったパンや焼き菓子、ソフトクリームなどが揃うグルテンフリーカフェ。かわいらしい内装と商品、テイクアウト対応が投稿の見どころ。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:128, name:"Gelato 9.", area:"世田谷区", region:"玉川", lat:35.616173, lng:139.625549,
   address:"東京都世田谷区玉川4-12-15 グランデュオ 1F", genre:"スイーツ", photos:[],
   description:"フレンチ出身のシェフが手掛ける旬の食材を使ったジェラート専門店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:129, name:"FAMILY RESTAURANT by NEW VALLEY", likes:21, area:"世田谷区", region:"玉川", lat:35.61573, lng:139.625641,
   address:"東京都世田谷区玉川4-5-6 グリーンテラスオジマ 1F", genre:"バー", photos:["images/like09.png"],
   description:"酒屋が運営し、多彩なワインやクラフトビールと食事を楽しめるレストラン。チキンやハンバーグなど子どもに親しみやすい料理、テラス席、子ども用食器がある。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:130, name:"fuwariの秘密基地", area:"世田谷区", region:"玉川台", lat:35.624104, lng:139.63237,
   address:"東京都世田谷区玉川台1-12-8 1F", genre:"スイーツ", photos:[],
   description:"子供にも人気なかき氷\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし／キッズチェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:131, name:"用賀倶楽部", area:"世田谷区", region:"玉川台", lat:35.624775, lng:139.629547,
   address:"東京都世田谷区玉川台2-17-16 世田谷マイスターハウス 1F", genre:"", photos:[],
   description:"広々とした店内で、テラス席でも食事ができます\n\n【子連れ情報】ベビーカー：要確認 お店へご相談ください。／個室：あり／ソファー席：あり／授乳室：なし／おむつ交換：なし／子供用食器：なし／キッズチェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:132, name:"ミンナトリエ", likes:31, area:"世田谷区", region:"玉川田園調布", lat:35.602154, lng:139.664917,
   address:"東京都世田谷区玉川田園調布2-13-18", genre:"", photos:["images/like01.png"],
   description:"自然光が入る落ち着いた空間で、身体にやさしいフードやスイーツを提供。見守り付きヨガや、個室を利用したランチ会・サークル活動にも対応する子育て世代歓迎の拠点。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:133, name:"イクラバル", area:"世田谷区", region:"用賀", lat:35.628174, lng:139.635925,
   address:"東京都世田谷区用賀3-14-9", genre:"バー", photos:[],
   description:"隠れた名店！用賀駅徒歩3分のロシア料理店\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:134, name:"田燕居", area:"世田谷区", region:"用賀", lat:35.628719, lng:139.633453,
   address:"東京都世田谷区用賀4-17-8 パインパレス １Ｆ", genre:"中華", photos:[],
   description:"落ち着きのある空間で、伝統的な中国料理を\n\n【子連れ情報】ベビーカー：要確認※要確認／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：あり／子供用食器：なし／お子様用チェアー：あり",
   features:{stroller:false, diaper:true, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:135, name:"サザンダイニング", area:"世田谷区", region:"用賀", lat:35.626167, lng:139.633255,
   address:"東京都世田谷区用賀4-4-8 第二福島ビル １Ｆ", genre:"イタリアン", photos:[],
   description:"用賀駅すぐのカジュアルイタリアン\n\n【子連れ情報】ベビーカーokで子供用チェアーもあるので子連れ利用にもピッタリ✨／ベビーカー：あり／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:136, name:"ダーリン・ドルチェ", likes:18, area:"世田谷区", region:"砧", lat:35.640831, lng:139.609238,
   address:"東京都世田谷区砧6-27-19 笑恵館", genre:"スイーツ", photos:["images/like14.png"],
   description:"2024年指定の『世田谷みやげ』特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:137, name:"アトリエそら豆", likes:18, area:"世田谷区", region:"砧", lat:35.640934, lng:139.608215,
   address:"東京都世田谷区砧6-29-5", genre:"", photos:["images/like14.png"],
   description:"2024年指定の『世田谷みやげ』特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:138, name:"オステリア エジリオ・サーラ", area:"世田谷区", region:"砧", lat:35.642422, lng:139.6082,
   address:"東京都世田谷区砧8-9-8", genre:"イタリアン", photos:[],
   description:"心と身体に優しいイタリアン\n\n【子連れ情報】お子様連れの方にはキッズメニューも／ベビーカー：あり／半個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:139, name:"コンディトライ・ニシキヤ", likes:18, area:"世田谷区", region:"祖師谷", lat:35.64325, lng:139.608368,
   address:"東京都世田谷区祖師谷3-32-3", genre:"", photos:["images/like14.png"],
   description:"2024年指定の『世田谷みやげ』特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:140, name:"ピッツェリア タラッリ", area:"世田谷区", region:"祖師谷", lat:35.644169, lng:139.608612,
   address:"東京都世田谷区祖師谷3-33-7 キクヤビル 1F", genre:"イタリアン", photos:[],
   description:"温かい家族経営のピッツェリア\n\n【子連れ情報】ピザの種類多く、テイクアウトもできます／ベビーカー：あり／個室：あり／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:141, name:"ミルデリス", area:"世田谷区", region:"祖師谷", lat:35.648579, lng:139.608261,
   address:"東京都世田谷区祖師谷4-23-17", genre:"ベーカリー", photos:[],
   description:"午前中に売り切れてしまうこともある人気のパン屋さん\n\n【子連れ情報】ベビーカー：なし／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:142, name:"PEAK SWELL COFFEE ROASTERS", likes:21, area:"世田谷区", region:"等々力", lat:35.607704, lng:139.646942,
   address:"東京都世田谷区等々力2-38-27 岩田ビル 2F", genre:"カフェ", photos:["images/like10.png"],
   description:"等々力渓谷前のロースタリーカフェ。こだわりのコーヒー、ドーナツ、フードを提供し、屋上テラスも利用可能。ベビーカーと犬同伴に対応している。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:143, name:"ゆうゆう食堂", area:"世田谷区", region:"等々力", lat:35.610264, lng:139.647552,
   address:"東京都世田谷区等々力3-19-16", genre:"和食", photos:[],
   description:"豚汁が自慢の定食屋(食堂)兼子供食堂\n\n【子連れ情報】ベビーカー：要確認 ※入り口段差があります。／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:144, name:"Cafe STREAM", area:"世田谷区", region:"等々力", lat:35.608311, lng:139.648712,
   address:"東京都世田谷区等々力3-4-1 玉川区民会館", genre:"カフェ", photos:[],
   description:"玉川区民会館内のカフェ\n\n【子連れ情報】ベビーカー：要確認要確認／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:145, name:"やぶ森", area:"世田谷区", region:"等々力", lat:35.608829, lng:139.647369,
   address:"東京都世田谷区等々力3-5-6", genre:"そば", photos:[],
   description:"1924年創業 等々力渓谷のお膝元で地元民のみならず観光客からも愛される蕎麦屋\n\n【子連れ情報】ベビーカー：要確認※要確認／個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:146, name:"平和食品工業", likes:18, area:"世田谷区", region:"等々力", lat:35.60844, lng:139.650421,
   address:"東京都世田谷区等々力4-6-1", genre:"和食", photos:["images/like14.png"],
   description:"2024年指定の『世田谷みやげ』特集で紹介。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:147, name:"洋風食堂 はしぐち亭", area:"世田谷区", region:"経堂", lat:35.649399, lng:139.637085,
   address:"東京都世田谷区経堂1-11-13 ウエダビル１F", genre:"和食", photos:[],
   description:"洋食店No.1に選ばれた絶品「手ごねハンバーグ」と名物「元祖ちとかライス」の店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:148, name:"七つの水仙", area:"世田谷区", region:"経堂", lat:35.653801, lng:139.633942,
   address:"東京都世田谷区経堂2-10-10", genre:"スイーツ", photos:[],
   description:"創業1991年、地域の人から愛されるケーキ屋さん\n\n【子連れ情報】ベビーカー：なし／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:149, name:"デリス", area:"世田谷区", region:"経堂", lat:35.651325, lng:139.634521,
   address:"東京都世田谷区経堂2-15-15", genre:"", photos:[],
   description:"経堂駅北口から徒歩約2分、行列のできる洋食店\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:150, name:"a-bridge／AELIAN", area:"世田谷区", region:"羽根木", lat:35.66383, lng:139.659103,
   address:"東京都世田谷区羽根木1-19-20 羽根木インターナショナルガーデンハウスA棟", genre:"カフェ", photos:[],
   description:"自然豊かな羽根木公園近くのカフェ\n\n【子連れ情報】キッズメニューもあるので、お子様との休憩やご家族、ママパパ友と…様々なシーンで利用できます／ベビーカー：なし／個室：なし／ソファー席：なし／授乳室：なし／おむつ交換：なし／子供用食器：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:151, name:"kitchen and CURRY", area:"世田谷区", region:"羽根木", lat:35.663918, lng:139.65863,
   address:"東京都世田谷区羽根木1-21-24 亀甲新い52", genre:"カレー", photos:[],
   description:"羽根木にある毎日でめ食べられる優しいカレー\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:false}},
  {id:152, name:"POKAPOKA", area:"世田谷区", region:"船橋", lat:35.657059, lng:139.621902,
   address:"東京都世田谷区船橋6-26-9 サンヒルズ希望ヶ丘 1F", genre:"ベーカリー", photos:[],
   description:"千歳船橋のイタリアンレストランと自家製パン\n\n【子連れ情報】テラス席はペットもok／ベビーカー：あり／個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:153, name:"CRAZY MAMA", area:"世田谷区", region:"若林", lat:35.650345, lng:139.663666,
   address:"東京都世田谷区若林2-41-1", genre:"", photos:[],
   description:"忙しいママパパさんを思った美味しくてお安いおにぎりやお弁当",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:154, name:"CAFE DICT", area:"世田谷区", region:"若林", lat:35.643082, lng:139.655212,
   address:"東京都世田谷区若林3-17-7", genre:"カフェ", photos:[],
   description:"松陰神社前駅から徒歩約1分の可愛いカフェ\n\n【子連れ情報】ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:true, privateRoom:false, tatami:true}},
  {id:155, name:"atelier de terrine maison okei", area:"世田谷区", region:"豪徳寺", lat:35.654335, lng:139.647385,
   address:"東京都世田谷区豪徳寺1-45-9 1F", genre:"フレンチ", photos:[],
   description:"築70年古民家を改装したビストロ\n\n【子連れ情報】1階はペットok／ベビーカー：あり／半個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:156, name:"Rarasand", area:"世田谷区", region:"豪徳寺", lat:35.651546, lng:139.646317,
   address:"東京都世田谷区豪徳寺1-8-5", genre:"カフェ", photos:[],
   description:"ご縁を結ぶ豪徳寺の和モダンカフェ\n\n【子連れ情報】ベビーカー：要確認※要確認／半個室：なし／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:157, name:"Bar & Dining emu", area:"世田谷区", region:"豪徳寺", lat:35.645409, lng:139.647568,
   address:"東京都世田谷区豪徳寺2-1-10 １F", genre:"イタリアン", photos:[],
   description:"味とボリュームが好評のイタリアン\n\n【子連れ情報】ベビーカー：あり／半個室：なし／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし／お子様用チェアー：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:158, name:"中国料理 柚子", area:"世田谷区", region:"赤堤", lat:35.653934, lng:139.642731,
   address:"東京都世田谷区赤堤1-16-21", genre:"中華", photos:[],
   description:"住宅街にひっそりと佇む本格中国料理\n\n【子連れ情報】ソファー席、半個室や個室、ベビーカーok等、子連れにも嬉しいサービスのレベルの高い中国料理をご家族で楽しんでみては✨／ベビーカー：あり／半個室：あり／ソファー席/座敷席：あり／授乳室：なし／おむつ交換スペース：なし／子供用食器：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:159, name:"世田谷 火龍園", area:"世田谷区", region:"赤堤", lat:35.657207, lng:139.644333,
   address:"東京都世田谷区赤堤2-11-14", genre:"中華", photos:[],
   description:"リゾートホテルのダイニングをイメージした世田谷火龍園\n\n【子連れ情報】ベビーカー：あり／個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし／子供用食器：あり／お子様用チェアー：あり",
   features:{stroller:true, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:true, privateRoom:true, tatami:false}},
  {id:160, name:"&tea", area:"世田谷区", region:"赤堤", lat:35.664913, lng:139.637192,
   address:"東京都世田谷区赤堤5-26-9 長尾ビル 1F", genre:"カフェ", photos:[],
   description:"絵本やおもちゃのある親子でゆったりすごせるカフェ\n\n【子連れ情報】キッズメニューや卵・牛乳・バターを使わないお菓子が用意されていたりとお子様連れに優しいカフェです／ベビーカー ：あり／個室：なし／授乳室：なし／おむつ交換台：なし／駐車場：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:161, name:"たつみや", area:"世田谷区", region:"赤堤", lat:35.665527, lng:139.638779,
   address:"東京都世田谷区赤堤5-31-1", genre:"スイーツ", photos:[],
   description:"世田谷みやげにも選ばれているたい焼き",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:162, name:"CORDE", area:"世田谷区", region:"野沢", lat:35.634537, lng:139.664856,
   address:"東京都世田谷区野沢4-24-1ヴィルヌーブタワー駒沢2F C-3", genre:"フレンチ", photos:[],
   description:"子連れ歓迎のビストロ。お子様メニュー、ソファ席、テイクアウト弁当あり。\n\n【子連れ情報】子連れ大歓迎のレストランでお弁当をテイクアウト♪／レストランはお子様メニューがあることや、ペットもokというところで、利用しやすく居心地の良い空間でした／今回、テイクアウト注文したお弁当は…／ベビーカー：あり／個室：なし／ソファー席/座敷席：あり／授乳室：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:163, name:"KOMAICHI & CAFE", area:"世田谷区", region:"駒沢", lat:35.630913, lng:139.656693,
   address:"東京都世田谷区駒沢1-20-7 グランメゾン駒沢パーク 2F", genre:"カフェ", photos:[],
   description:"ボリューミーなカフェご飯が魅力的な駒沢公園すぐのカフェ\n\n【子連れ情報】ベビーカー ：なし／半個室：なし／ソファー席：あり／授乳室(施設内)：なし／おむつ交換：あり／子供用食器：なし／キッズチェアー：なし",
   features:{stroller:false, diaper:true, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:164, name:"PÂTISSERIE NAOKI 駒沢店", area:"世田谷区", region:"駒沢", lat:35.632668, lng:139.66066,
   address:"東京都世田谷区駒沢1-4-12", genre:"スイーツ", photos:[],
   description:"クリスマスケーキはもう何度食べただろう、というくらいお世話になっているケーキ屋さん",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:165, name:"五大", area:"世田谷区", region:"駒沢", lat:35.630673, lng:139.653183,
   address:"東京都世田谷区駒沢3-18-2 オザワビル ２Ｆ", genre:"", photos:[],
   description:"毎日、蟻巣石の石臼で自家製粉\n\n【子連れ情報】駐車場は8台完備、店内はとても広くソファー席やお座敷、個室等様々なシーンで利用できます☘／ベビーカー入店もできるので、赤ちゃん連れにもおススメ／ペット専用のお席も／ベビーカー：あり／個室：あり／ソファー席/座敷席：あり／授乳室：なし",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:166, name:"韓々", area:"世田谷区", region:"駒沢", lat:35.630413, lng:139.653183,
   address:"東京都世田谷区駒沢3-18-2 ３Ｆ", genre:"韓国", photos:[],
   description:"客席は個室、半個室！家族連れに好評な焼肉店\n\n【子連れ情報】／駐車場完備なので、車で利用できます／ベビーカー：要確認※要確認／個室：あり／ソファー席/座敷席：なし／授乳室：なし／おむつ交換スペース：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:167, name:"MIO", area:"世田谷区", region:"駒沢", lat:35.628025, lng:139.656067,
   address:"東京都世田谷区駒沢4-12-22 1F", genre:"", photos:[],
   description:"駒沢公園入り口向かいにあるレストラン\n\n【子連れ情報】ベビーカー ：なし／半個室：あり／ソファー席：あり／授乳室(施設内)：なし／おむつ交換：なし／子供用食器：なし／キッズチェアー：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:true}},
  {id:168, name:"Osteria C3（オステリア チートレ）", likes:24, area:"世田谷区", region:"駒沢", lat:35.624065, lng:139.655304,
   address:"東京都世田谷区駒沢5-18-7", genre:"イタリアン", photos:["images/like07.png"],
   description:"駒沢公園近くのイタリア料理店。ランチ限定の子ども向けメニューがあり、料理と接客、落ち着いた雰囲気が高く紹介されている。店舗は地下のためベビーカー利用時は注意。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:true, kidsTableware:false, privateRoom:false, tatami:true}},
  {id:169, name:"富錦樹台菜香檳（フージンツリー）", area:"中央区", region:"日本橋室町", lat:35.687458, lng:139.77272,
   address:"東京都中央区日本橋室町3-2-1 COREDO室町テラス 2F", genre:"中華", photos:[],
   description:"富錦樹台菜香檳(フージンツリー)\n\n【子連れ情報】ベビーカー：あり(コレド室町テラス内にあるのでエレベーターも館内も広々✨ 店内、テラスもご用意ベビーカーを置いても余裕の広さです♪)／授乳室：あり(コレド室町館内にあります)／個室：なし",
   features:{stroller:true, diaper:false, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:170, name:"ALL DAY HOME 武蔵小山店", area:"品川区", region:"小山", lat:35.620892, lng:139.706879,
   address:"東京都品川区小山2-6-17", genre:"", photos:[],
   description:"ALL DAY HOME 武蔵小山\n\n【子連れ情報】ベビーカー：あり／個室：なし／授乳スペース：あり／おむつ交換台：あり／駐車場：なし",
   features:{stroller:true, diaper:true, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:171, name:"dish&table（ディッシュアンドテーブル）", area:"大田区", region:"北千束", lat:35.608711, lng:139.685104,
   address:"東京都大田区北千束1-50-3", genre:"", photos:[],
   description:"dish&table （ディッシュアンドテーブル）\n\n【子連れ情報】テイクアウト",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:172, name:"フタバフルーツパーラー 新宿マルイ本館店", area:"新宿区", region:"新宿", lat:35.691158, lng:139.703949,
   address:"東京都新宿区新宿3-30-13 新宿マルイ本館 5F", genre:"", photos:[],
   description:"広々としたおしゃれな店内\n\n【子連れ情報】ベビーカー：あり／授乳室：あり(新宿マルイ本館内)／個室：なし／駐車場：あり",
   features:{stroller:true, diaper:false, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:173, name:"ナンマンゴギ", area:"新宿区", region:"百人町", lat:35.699108, lng:139.702118,
   address:"東京都新宿区百人町1-1-22 ひかりビル1F", genre:"", photos:[],
   description:"セナさん",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:174, name:"グルマンマーケット紀ノ国屋 渋谷スクランブルスクエア店", likes:29, area:"渋谷区", region:"渋谷", lat:35.657951, lng:139.702316,
   address:"東京都渋谷区渋谷2-24-12", genre:"スイーツ", photos:["images/like02.png"],
   description:"大きなパイナップルを盛り付けたソフトクリームが主役。濃厚なミルク感と果肉の甘さが特徴で、渋谷駅直結施設内のため親子でも立ち寄りやすい。",
   features:{stroller:false, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:175, name:"菜な 渋谷マークシティ店", area:"渋谷区", region:"道玄坂", lat:35.657936, lng:139.698624,
   address:"東京都渋谷区道玄坂1-12-5 渋谷マークシティ RESTAURANTS AVENUE 4F", genre:"", photos:[],
   description:"渋谷駅直結の子連れに優しいお店\n\n【子連れ情報】大小さまざまな個室もあるので予約をして行くのがおススメです／ベビーカー ：あり／個室：あり／おむつ交換台：あり(同フロア)／駐車場：なし",
   features:{stroller:true, diaper:true, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:176, name:"杜カフェ", area:"羽村市", region:"小作台（投稿内に番地の記載なし）", lat:35.777363, lng:139.303391,
   address:"東京都羽村市小作台", genre:"カフェ", photos:[],
   description:"子供から大人まで楽しめる日替わりカフェ\n\n【子連れ情報】ベビーカー -／個室：なし／授乳室：あり／おむつ交換台：あり／駐車場：あり",
   features:{stroller:false, diaper:true, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:177, name:"プラレールが走るカフェ 子鉄", area:"荒川区", region:"西尾久", lat:35.750435, lng:139.756714,
   address:"東京都荒川区西尾久7-19-11", genre:"カフェ", photos:[],
   description:"天井まで届きそうな巨大レイアウトでプラレールが走っているので、子供達も大興奮間違いなし\n\n【子連れ情報】子供向けの食事やキッズスペース、おむつ替えスペース、お子さま用のイス、ベビーカー置き場、無料Wi-Fiも完備。／ベビーカー：あり／個室：なし／おむつ替え台：あり／駐車場：なし",
   features:{stroller:true, diaper:true, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:178, name:"仮面ライダー ザ ダイナー", area:"豊島区", region:"西池袋", lat:35.731945, lng:139.708954,
   address:"東京都豊島区西池袋1-21-9", genre:"", photos:[],
   description:"子供も大人も大興奮、公式レストランはここだけ\n\n【子連れ情報】ベビーカー/子供用イス：あり(予約の際に備考欄へ記載)／ベビーベッド・おむつ交換スペース：なし／個室：あり／駐車場：なし",
   features:{stroller:false, diaper:false, nursing:false, babyChair:true, kidsMenu:false, kidsTableware:false, privateRoom:true, tatami:false}},
  {id:179, name:"たまごのきもち。武蔵小杉店", likes:19, area:"川崎市", region:"中原区小杉町", lat:35.574787, lng:139.658401,
   address:"神奈川県川崎市中原区小杉町3-430-1 千里ビル1F", genre:"", photos:["images/like13.png"],
   description:"目の前で卵を開く演出と濃厚なチーズソースが特徴のオムライス専門店。個室が多く、子ども向けメニュー・食器を用意。ベビーカーは入口で畳んで預けられる。",
   features:{stroller:true, diaper:false, nursing:false, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
  {id:180, name:"KOSUGI CAFE nappa69", area:"川崎市", region:"中原区小杉町", lat:35.574684, lng:139.657257,
   address:"神奈川県川崎市中原区小杉町3-600 Kosugi 3rd Avenue 202-2", genre:"カフェ", photos:[],
   description:"新鮮野菜を使ったプレートランチがおススメ\n\n【子連れ情報】店内は明るく、広々としていてベビーカーを横に食事を楽しまれているママがとても多いです／店内に授乳室もあるのが嬉しいポイント✌／ベビーカー：あり／個室：なし／授乳スペース：あり／おむつ交換台：なし／駐車場：あり",
   features:{stroller:true, diaper:false, nursing:true, babyChair:false, kidsMenu:false, kidsTableware:false, privateRoom:false, tatami:false}},
];

const FEATURE_LABELS = {
  stroller: "ベビーカー可",
  diaper: "おむつ替え",
  nursing: "授乳室",
  babyChair: "ベビーチェア",
  kidsMenu: "キッズメニュー",
  kidsTableware: "子供用食器",
  privateRoom: "個室・半個室",
  tatami: "座敷・ソファー"
};
